version: "3.8"
services:
<<<<<<< HEAD
  # auth:
  #   hostname: auth
  #   build: auth/
  #   volumes:
  #     - './auth/:/app'
  #     - '/app/node_modules'
  #   environment:
  #     PORT: 5000
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mariadb
  #   command: bash -c "npm run server"
  #   networks:
  #     - db_auth
  #     - auth_business
  #     - auth_mailer
=======
  auth:
    hostname: auth
    build: 
      dockerfile: auth/Dockerfile
      context: ./
    volumes:
      - './auth/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: 5000
      DATABASE_URL: mysql://lodl-admin:changeme@mariadb:3306/lodl-stock
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    command: bash -c "npm run server:watch"
    networks:
      - db_auth
      - auth_business
      - auth_mailer
>>>>>>> 438428f ([NEW] added register and login routes in the auth service)

  business:
    hostname: business
    build:
      dockerfile: business/Dockerfile
      context: ./
    volumes:
      - './business/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: 5001
      DATABASE_URL: mysql://lodl-admin:changeme@mariadb:3306/lodl-stock
    ports:
      - "5001:5001"
    depends_on:
      - mariadb
      # - auth
    command: bash -c "npx prisma db push --accept-data-loss && npm run server:watch"
    networks:
      - db_business
      - auth_business

  mailer:
    hostname: mailer
    build:
      dockerfile: mailer/Dockerfile
      context: ./
    volumes:
      - './mailer/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: 5002
      DATABASE_URL: mysql://lodl-admin:changeme@mariadb:3306/lodl-stock
      user: ${user}
      pass: ${pass}
    ports:
      - "5002:5002"
    depends_on:
      - mariadb
      - business
      # - auth
    command: bash -c "npx prisma db push --accept-data-loss ; npm run server:watch"
    networks:
      - db_mailer
      - auth_mailer

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: lodl-stock
      MYSQL_USER: lodl-admin
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    networks:
      - db_business
      - db_admin
      - db_auth
      - db_mailer
    restart: on-failure
    volumes:
      - db-mariadb:/var/lib/mysql

  dbadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - db_admin
    ports:
      - "8080:80"

networks:
  db_auth:
  db_business:
  db_mailer:
  auth_business:
  auth_mailer:
  db_admin:

volumes:
  db-mariadb:
