version: "3.8"
services:
  auth:
    hostname: auth
    build:
      dockerfile: auth/Dockerfile
      context: ./
    volumes:
      - './auth/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${AUTH_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - mariadb
    # Auth service should start first after db service, so let it update
    # database schema
    command: bash -c "sleep 10 ; npx prisma db push --accept-data-loss && npm run server:watch"
    networks:
      - db_auth
      - auth_business
      - auth_mailer
      - prometheus

  business:
    hostname: business
    build:
      dockerfile: business/Dockerfile
      context: ./
    volumes:
      - './business/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${BUSINESS_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
    ports:
      - "${BUSINESS_PORT}:${BUSINESS_PORT}"
    depends_on:
      - mariadb
      - auth
    command: bash -c "sleep 10 ; npm run server:watch"
    networks:
      - db_business
      - auth_business
      - prometheus

  mailer:
    hostname: mailer
    build:
      dockerfile: mailer/Dockerfile
      context: ./
    volumes:
      - './mailer/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${MAILER_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
      mailUser: ${mailUser}
      mailPass: ${mailPass}
    ports:
      - "${MAILER_PORT}:${MAILER_PORT}"
    depends_on:
      - mariadb
      - business
      - auth
    command: bash -c "sleep 10 ; npm run server:watch"
    networks:
      - db_mailer
      - auth_mailer
      - prometheus

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - db_business
      - db_admin
      - db_auth
      - db_mailer
    restart: on-failure
    volumes:
      - db-mariadb:/var/lib/mysql

  dbadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - db_admin
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus
    depends_on:
      - auth
      - business
      - mailer

networks:
  db_auth:
  db_business:
  db_mailer:
  auth_business:
  auth_mailer:
  db_admin:
  prometheus:

volumes:
  db-mariadb:
  prometheus:
