version: "3.8"
services:
  auth:
    hostname: auth
    image: mariateaca/lodl-stock-auth:latest
    volumes:
      - './auth/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${AUTH_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    # Auth service should start first after db service, so let it update
    # database schema
    command: bash -c "sleep 10 ; npx prisma db push --accept-data-loss && npm run server:watch"
    networks:
      - db_auth
      - auth_business
      - auth_mailer
      - prometheus

  business:
    hostname: business
    image: mariateaca/lodl-stock-business:latest
    volumes:
      - './business/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${BUSINESS_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
    ports:
      - "5001:5001"
    depends_on:
      - mariadb
      - auth
    command: bash -c "sleep 10 ; npm run server:watch"
    networks:
      - db_business
      - auth_business
      - prometheus

  mailer:
    hostname: mailer
    image: mariateaca/lodl-stock-mailer:latest
    volumes:
      - './mailer/src:/app/src'
      - '/app/node_modules'
    environment:
      PORT: ${MAILER_PORT}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}
      mailUser: ${mailUser}
      mailPass: ${mailPass}
    ports:
      - "5002:5002"
    depends_on:
      - mariadb
      - business
      - auth
    command: bash -c "sleep 10 ; npm run server:watch"
    networks:
      - db_mailer
      - auth_mailer
      - prometheus

  mariadb:
    deploy:
      replicas: 1
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - db_business
      - db_admin
      - db_auth
      - db_mailer
    volumes:
      - db-mariadb:/var/lib/mysql

  dbadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - db_admin
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prom_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - prometheus
      - network_grafana
    depends_on:
      - auth
      - business
      - mailer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    networks:
      - network_grafana

networks:
  db_auth:
  db_business:
  db_mailer:
  auth_business:
  auth_mailer:
  db_admin:
  prometheus:
  network_grafana:

volumes:
  db-mariadb:
  prom_data:
  grafana-storage:
