name: Docker Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - './auth'
      - './business'
      - './mailer'
      - './db'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Build and Push Images to Docker Hub
        env:
          CI_REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          CI_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
          docker build --pull -t $CI_REGISTRY_USER/lodl-stock-auth -f auth/Dockerfile .
          docker push $CI_REGISTRY_USER/lodl-stock-auth
          docker build --pull -t $CI_REGISTRY_USER/lodl-stock-business -f business/Dockerfile .
          docker push $CI_REGISTRY_USER/lodl-stock-business
          docker build --pull -t $CI_REGISTRY_USER/lodl-stock-mailer -f mailer/Dockerfile .
          docker push $CI_REGISTRY_USER/lodl-stock-mailer
