name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pull-code:
    uses: ./.github/workflows/pull.yaml
    secrets: inherit
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploy through Portainer on DigitalOcean
        run: |
          curl -k -XPOST http://104.248.131.77:9000/api/stacks/webhooks/7898ce5d-34ed-4112-a141-f94bf64d1917
