name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pull-code:
    uses: ./.github/workflows/pull.yaml
    secrets: inherit
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.DOCKER_PG_URL}}
          debug: true
          script: |
            ip a s
            docker swarm init --advertise-addr ${{secrets.DOCKER_PG_PRIV_URL}}
            echo "Swarm init"
            docker compose -f stack.yml build
            echo "Stack built"
            docker stack deploy --compose-file stack.yml lodl-stock
            echo "Stack deployed!"
