name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.DOCKER_PG_URL}}
          script: |
            run: docker swarm init --advertise-addr ${{secrets.DOCKER_PG_PRIV_URL}}
            run: docker compose -f stack.yml build
            run: docker stack deploy --compose-file stack.yml lodl-stock
