name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploy through Portainer on DigitalOcean
        run: |
          curl -k -XPOST https://ip172-18-0-123-cp68388l2o9000dcg460-9443.direct.labs.play-with-docker.com/api/stacks/webhooks/a8cc09bc-6879-441f-870f-a9b5eb1b54ec
