name: pull-code
on:
  workflow_dispatch:
  workflow_call:

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.DOCKER_PG_URL}}
          username: ${{secrets.DOCKER_PG_USERNAME}}
          debug: true
          script: |
            ls lodl-stock || git pull https://github.com/lodl-stock/lodl-stock.git
            cd lodk-stock/
            git checkout main
            git fetch origin
            git reset --hard origin/main
